In [19]:
import pandas as pd

df = pd.read_parquet("../data/crossmatch_cache/crossmatch_merged_1.0arcsec.parquet")
df.head()

,Z,_dist_arcsec,_healpix_29,additional_names,arxiv_id,coordinate_resolution_name,dec_mentions,dec_spectra,discussion_extent,evidence_quote_count,...,ra_mentions,ra_spectra,resolver_agent_confidence,resolver_api_or_agent,resolver_method_used,spectrum,uat_terms,wiki_entity_id,survey,survey_metadata
0,0.893283,0.257587,56333355682100,[],astro-ph/0611120,0259+0048,0.803780,0.803780,short_paragraph,1,...,44.998744,44.998672,high,subagent,resolved_from_paper,"{'flux': [21.638826, 21.634905, 21.63099, 21.6...","[X-ray quasars, Quasars]",gmw_00012936,sdss,"{'VDISP': 0.0, 'VDISP_ERR': 0.0, 'Z_ERR': 0.00..."
1,0.568009,0.317206,56334824474469,[],2203.11964,SDSS J030000.57+004828.0,0.807752,0.807797,short_paragraph,1,...,45.002396,45.002320,high,subagent,resolved_from_ned,"{'flux': [3.7452986, 3.7441378, 3.7429783, 3.7...","[Quasars, Broad-absorption line quasar, Active...",gmw_00000950,sdss,"{'VDISP': 850.0, 'VDISP_ERR': -3.0, 'Z_ERR': 7..."
2,0.568009,0.317206,56334824474469,[J0300],2402.10581,SDSS J030000.56+004828.0,0.807752,0.807797,paper_focus,2,...,45.002396,45.002320,high,subagent,resolved_from_ned,"{'flux': [3.7452986, 3.7441378, 3.7429783, 3.7...","[Broad-absorption line quasar, Quasars, Active...",gmw_00000950,sdss,"{'VDISP': 850.0, 'VDISP_ERR': -3.0, 'Z_ERR': 7..."
3,0.568009,0.185631,56334824881092,[],1507.07247,J030000.57+004828.0,0.807780,0.807797,short_paragraph,1,...,45.002369,45.002320,high,subagent,resolved_from_paper,"{'flux': [3.7452986, 3.7441378, 3.7429783, 3.7...","[Broad-absorption line quasar, Quasars, Active...",gmw_00000950,sdss,"{'VDISP': 850.0, 'VDISP_ERR': -3.0, 'Z_ERR': 7..."
4,0.218987,0.131972,37031847698858078,[021348],1911.07854,021348 (J0213),12.997640,12.997660,multiple_paragraphs,3,...,33.452201,33.452232,high,subagent,resolved_from_paper,"{'flux': [15.163446, 15.173299, 15.183151, 15....","[Lyman-break galaxies, Active galactic nuclei,...",gmw_00012618,sdss,"{'VDISP': 73.03389739990234, 'VDISP_ERR': 25.0..."

In [18]:
df['object_id'].astype(int)

ValueError: invalid literal for int() with base 10: "b'    462849895556999168'"

In [22]:
df[df['object_id'] == '39632951360620188']

,Z,_dist_arcsec,_healpix_29,additional_names,arxiv_id,coordinate_resolution_name,dec_mentions,dec_spectra,discussion_extent,evidence_quote_count,...,ra_mentions,ra_spectra,resolver_agent_confidence,resolver_api_or_agent,resolver_method_used,spectrum,uat_terms,wiki_entity_id,survey,survey_metadata
4575,0.197513,0.133871,643592388338055503,[],2207.01648,2MASX J14344537+3328211,33.472399,33.47238,short_paragraph,1,...,218.688998,218.688959,medium,subagent,resolved_from_paper,"{'flux': [-13.777952, 18.727985, 16.35055, 1.0...","[Giant radio galaxies, Fanaroff-Riley radio ga...",gmw_00006565,desi,"{'VDISP': None, 'VDISP_ERR': None, 'Z_ERR': No..."

In [6]:
df[df['survey'] == 'desi']['_healpix_29'].nunique()

361